apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gulel-redis-persistent-volume
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  storageClassName: slow
  selector:
    matchLabels:
      release: "stable"
