apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-redis
  labels:
    app: redis-redis
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  mountOptions:
    - hard
  nfs:
    path:  "/data/pvc_nfs"
    server: nfs.ilinux.io
